version: '3'

services:
  opensearch-node1:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-2.17.0}
    container_name: opensearch-node1
    environment:
      - cluster.name=${CLUSTER_NAME:-opensearch-cluster}
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD:-test1234!}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ../../schema/synonyms.txt:/usr/share/opensearch/config/synonyms.txt
    ports:
      - ${OPENSEARCH_PORT:-9200}:9200
      - ${OPENSEARCH_PERFORMANCE_PORT:-9600}:9600
    networks:
      - opensearch-net

  opensearch-node2:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-2.17.0}
    container_name: opensearch-node2
    environment:
      - cluster.name=${CLUSTER_NAME:-opensearch-cluster}
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD:-test1234!}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ../../schema/synonyms.txt:/usr/share/opensearch/config/synonyms.txt
    networks:
      - opensearch-net

  opensearch-node3:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-2.17.0}
    container_name: opensearch-node3
    environment:
      - cluster.name=${CLUSTER_NAME:-opensearch-cluster}
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD:-test1234!}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data3:/usr/share/opensearch/data
      - ../../schema/synonyms.txt:/usr/share/opensearch/config/synonyms.txt
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH_DASHBOARDS_VERSION:-2.17.0}
    container_name: opensearch-dashboards
    ports:
      - ${DASHBOARDS_PORT:-5601}:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200","https://opensearch-node3:9200"]'
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1
      - opensearch-node2
      - opensearch-node3

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:

networks:
  opensearch-net:
    driver: bridge
